server:
  port: 9988

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aeesgsdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user
    password: user
  application:
    name: aeesgs-plateform

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


info:
  application:
    name: aeesgs-backend
    version: '@project.version@'
